// Build downloadable native-project skeletons (Android Gradle / iOS Xcode /
// Flutter) from the IDE's in-memory files. These are intentionally minimal:
// the goal is to give the user something they can open in Android Studio,
// Xcode, or `flutter run` locally — not a full production scaffold.
import JSZip from "jszip";

export type NativeTarget = "android" | "ios" | "flutter";

export interface MobileSourceFile {
  path: string;
  content: string;
  isAsset?: boolean;
  // base64 (no data: prefix) when isAsset is true
  base64?: string;
}

export interface BuildOpts {
  projectName: string;
  files: MobileSourceFile[];
}

const sanitize = (s: string) => s.replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/^_+|_+$/g, "") || "MobileApp";
const pkgSafe = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "");

function addUserFiles(zip: JSZip, baseDir: string, files: MobileSourceFile[]) {
  for (const f of files) {
    const target = `${baseDir}/${f.path}`;
    if (f.isAsset && f.base64) zip.file(target, f.base64, { base64: true });
    else zip.file(target, f.content);
  }
}

export async function buildAndroidZip({ projectName, files }: BuildOpts): Promise<Blob> {
  const zip = new JSZip();
  const appName = sanitize(projectName);
  const pkgId = `com.example.${pkgSafe(projectName) || "mobileapp"}`;
  const pkgPath = pkgId.replace(/\./g, "/");

  // Detect a user-provided MainActivity.kt
  const userMain = files.find((f) => /MainActivity\.kt$/i.test(f.path));
  const userMainSrc = userMain?.content ?? `package ${pkgId}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material3.Text
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface

class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      MaterialTheme {
        Surface { Text("Hello from ${appName}") }
      }
    }
  }
}
`;

  zip.file("settings.gradle.kts", `rootProject.name = "${appName}"
include(":app")
`);
  zip.file("build.gradle.kts", `// Top-level build file
plugins {
  id("com.android.application") version "8.5.0" apply false
  id("org.jetbrains.kotlin.android") version "1.9.24" apply false
}
`);
  zip.file("gradle.properties", `org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
kotlin.code.style=official
`);
  zip.file("README.md", `# ${appName}

Generated by Mobile IDE Playground. Open this folder in **Android Studio**
(File → Open) and let Gradle sync. Then press ▶ Run.

- Package id: \`${pkgId}\`
- Min SDK: 24 · Target SDK: 34
- Kotlin + Jetpack Compose

Your code lives at \`app/src/main/java/${pkgPath}/MainActivity.kt\`.
`);

  zip.file("app/build.gradle.kts", `plugins {
  id("com.android.application")
  id("org.jetbrains.kotlin.android")
}

android {
  namespace = "${pkgId}"
  compileSdk = 34
  defaultConfig {
    applicationId = "${pkgId}"
    minSdk = 24
    targetSdk = 34
    versionCode = 1
    versionName = "1.0"
  }
  buildFeatures { compose = true }
  composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }
  kotlinOptions { jvmTarget = "17" }
}

dependencies {
  implementation("androidx.core:core-ktx:1.13.1")
  implementation("androidx.activity:activity-compose:1.9.0")
  implementation(platform("androidx.compose:compose-bom:2024.06.00"))
  implementation("androidx.compose.material3:material3")
  implementation("androidx.compose.ui:ui-tooling-preview")
}
`);

  zip.file("app/src/main/AndroidManifest.xml", `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <application
    android:label="${appName}"
    android:theme="@style/Theme.Material3.DayNight.NoActionBar">
    <activity android:name=".MainActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
`);

  zip.file(`app/src/main/java/${pkgPath}/MainActivity.kt`, userMainSrc);

  // Also drop the user's original files for reference
  addUserFiles(zip, "user-sources", files);

  return zip.generateAsync({ type: "blob" });
}

export async function buildIosZip({ projectName, files }: BuildOpts): Promise<Blob> {
  const zip = new JSZip();
  const appName = sanitize(projectName);

  const userContent = files.find((f) => /ContentView\.swift$/i.test(f.path));
  const contentViewSrc = userContent?.content ?? `import SwiftUI

struct ContentView: View {
  var body: some View {
    Text("Hello from ${appName}")
      .padding()
  }
}

#Preview { ContentView() }
`;

  zip.file("README.md", `# ${appName}

Generated by Mobile IDE Playground. To run locally:

1. Open **Xcode** → File → New → Project → iOS App.
2. Name it \`${appName}\`, choose **SwiftUI** + **Swift**.
3. Replace the generated \`ContentView.swift\` and \`${appName}App.swift\`
   with the files in this archive.
4. Press ▶ to build & run on the iOS Simulator.

> Xcode requires macOS; iOS apps can't be compiled in the browser.
`);

  zip.file(`${appName}/${appName}App.swift`, `import SwiftUI

@main
struct ${appName}App: App {
  var body: some Scene {
    WindowGroup { ContentView() }
  }
}
`);

  zip.file(`${appName}/ContentView.swift`, contentViewSrc);

  zip.file(`${appName}/Info.plist`, `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleDisplayName</key><string>${appName}</string>
  <key>CFBundleIdentifier</key><string>com.example.${pkgSafe(projectName) || "mobileapp"}</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
</dict></plist>
`);

  addUserFiles(zip, "user-sources", files);
  return zip.generateAsync({ type: "blob" });
}

export async function buildFlutterZip({ projectName, files }: BuildOpts): Promise<Blob> {
  const zip = new JSZip();
  const appName = pkgSafe(projectName) || "mobile_app";

  const userMain = files.find((f) => /(^|\/)main\.dart$/i.test(f.path));
  const mainSrc = userMain?.content ?? `import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: '${appName}',
        home: Scaffold(
          appBar: AppBar(title: const Text('${appName}')),
          body: const Center(child: Text('Hello from Flutter')),
        ),
      );
}
`;

  zip.file("README.md", `# ${appName}

Generated by Mobile IDE Playground.

\`\`\`
flutter create ${appName}
# then copy lib/main.dart and pubspec.yaml from this archive over the generated files
flutter run
\`\`\`

Requires the Flutter SDK (https://flutter.dev/docs/get-started/install).
`);

  zip.file("pubspec.yaml", `name: ${appName}
description: Generated by Mobile IDE Playground.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
`);

  zip.file("lib/main.dart", mainSrc);

  addUserFiles(zip, "user-sources", files);
  return zip.generateAsync({ type: "blob" });
}

export function detectNativeTarget(language: string, files: MobileSourceFile[]): NativeTarget {
  if (language === "swift") return "ios";
  if (language === "dart") return "flutter";
  if (language === "kotlin") return "android";
  if (files.some((f) => /\.swift$/i.test(f.path))) return "ios";
  if (files.some((f) => /\.dart$/i.test(f.path))) return "flutter";
  return "android";
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
