/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground.index'
import { Route as PlaygroundWebRouteImport } from './routes/playground.web'
import { Route as PlaygroundMobileRouteImport } from './routes/playground.mobile'
import { Route as PlaygroundIdeRouteImport } from './routes/playground.ide'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundWebRoute = PlaygroundWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundMobileRoute = PlaygroundMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundIdeRoute = PlaygroundIdeRouteImport.update({
  id: '/ide',
  path: '/ide',
  getParentRoute: () => PlaygroundRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/tools': typeof ToolsRoute
  '/playground/ide': typeof PlaygroundIdeRoute
  '/playground/mobile': typeof PlaygroundMobileRoute
  '/playground/web': typeof PlaygroundWebRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRoute
  '/playground/ide': typeof PlaygroundIdeRoute
  '/playground/mobile': typeof PlaygroundMobileRoute
  '/playground/web': typeof PlaygroundWebRoute
  '/playground': typeof PlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/tools': typeof ToolsRoute
  '/playground/ide': typeof PlaygroundIdeRoute
  '/playground/mobile': typeof PlaygroundMobileRoute
  '/playground/web': typeof PlaygroundWebRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/tools'
    | '/playground/ide'
    | '/playground/mobile'
    | '/playground/web'
    | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools'
    | '/playground/ide'
    | '/playground/mobile'
    | '/playground/web'
    | '/playground'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/tools'
    | '/playground/ide'
    | '/playground/mobile'
    | '/playground/web'
    | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRouteWithChildren
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/web': {
      id: '/playground/web'
      path: '/web'
      fullPath: '/playground/web'
      preLoaderRoute: typeof PlaygroundWebRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/mobile': {
      id: '/playground/mobile'
      path: '/mobile'
      fullPath: '/playground/mobile'
      preLoaderRoute: typeof PlaygroundMobileRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/ide': {
      id: '/playground/ide'
      path: '/ide'
      fullPath: '/playground/ide'
      preLoaderRoute: typeof PlaygroundIdeRouteImport
      parentRoute: typeof PlaygroundRoute
    }
  }
}

interface PlaygroundRouteChildren {
  PlaygroundIdeRoute: typeof PlaygroundIdeRoute
  PlaygroundMobileRoute: typeof PlaygroundMobileRoute
  PlaygroundWebRoute: typeof PlaygroundWebRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

const PlaygroundRouteChildren: PlaygroundRouteChildren = {
  PlaygroundIdeRoute: PlaygroundIdeRoute,
  PlaygroundMobileRoute: PlaygroundMobileRoute,
  PlaygroundWebRoute: PlaygroundWebRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}

const PlaygroundRouteWithChildren = PlaygroundRoute._addFileChildren(
  PlaygroundRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRouteWithChildren,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
